# Generated by Django 3.2.14 on 2022-07-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220717_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='top_3_feedback',
        ),
    ]
