# Generated by Django 3.2.14 on 2022-07-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_feedback_feedback_top_3_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera'),
        ),
    ]
