# Generated by Django 3.2.14 on 2022-07-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_feedback_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='camera_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.camera'),
        ),
    ]
