# Generated by Django 3.2.14 on 2022-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_crowd_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
