# Generated by Django 3.2.14 on 2022-07-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220726_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='loayalty_points',
            new_name='loyalty_points',
        ),
    ]
