# Generated by Django 3.2.14 on 2022-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderedproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
    ]
