# Generated by Django 3.2.14 on 2022-07-27 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_loyaltydiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowd',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
