# Generated by Django 3.2.14 on 2022-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_crowd_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('branch', models.PositiveIntegerField(choices=[(1, 'Branch 1'), (2, 'Branch 2'), (3, 'Branch 3'), (4, 'Branch 4')], default=1)),
            ],
        ),
    ]
