# Generated by Django 3.2.14 on 2022-08-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
