import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from './theme';

const styles = StyleSheet.create({
  descriptionBg: {
    height: SIZES.height * 0.1,
    overflow: 'hidden',
  },
  descriptionBgFull: {},
  emptyCartContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flex: 1,
  },
  emptyCartMessage: {
    color: COLORS.third,
    fontSize: 15,
    textAlign: 'center',
    marginTop: -SIZES.height * 0.1,
  },
  centerFlex: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: 12,
    fontSize: 22,
    fontWeight: 'bold',
  },
  buttonStyle: {
    backgroundColor: COLORS.black,
    color: COLORS.white,
    height: 55,
    width: SIZES.width * 0.6,
    alignItems: 'center',
    borderRadius: 30,
    marginTop: 15,
  },
  rowFlex2: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    alignContent: 'center',
  },
  rowFlex22: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  colorDot1: {
    backgroundColor: '#111111',
    width: 15,
    height: 15,
    marginLeft: 5,
    borderRadius: 30,
    marginTop: 10,
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  rowFlex1: {
    height: 120,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignContent: 'center',
  },
  headerText: {
    color: COLORS.black,
    fontSize: 15,
    width: SIZES.width * 0.5,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  headerText2: {
    color: '#000000',
    fontSize: 15,
    width: SIZES.width * 0.5,
    textAlign: 'center',
    marginTop: 4,
  },
  bookItemContainer: {
    flexDirection: 'row',
    padding: 10,
  },
  thumbnail: {
    width: 100,
    height: 90,
  },
  bookItemMetaContainer: {
    padding: 5,
    paddingLeft: 10,
  },
  textTitle: {
    fontSize: 22,
  },
  sizeText: {
    fontSize: 13,
    fontWeight: '300',
    marginLeft: 10,
    marginTop: 10,
  },
  buttonContainer: {
    position: 'absolute',
    top: 110,
    left: 10,
  },
  button: {
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    padding: 5,
  },
  buttonText: {
    fontSize: 22,
    color: COLORS.white,
  },

  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonScan: {
    // borderRadius: 20,
    color: COLORS.black,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#EEEEEE',
    borderRadius: 5,
    width: 140,
  },
  textStyle: {
    color: COLORS.black,
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 20,
    textAlign: 'left',
    color: '#C54F4F',
  },
  modalText2: {
    marginBottom: 15,
    marginTop: 15,
    textAlign: 'left',
    color: '#000000',
  },
  child: {
    width: SIZES.width,
  },
  banner: {
    marginTop: -30,
    backgroundColor: COLORS.primary,
    width: SIZES.width * 0.9,
    height: 50,
    overflow: 'hidden',
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  rowFlex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  rowFlexScanRes: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 30,
    marginRight: 10,
    marginBottom: 10,
    marginTop: 10,
  },
  rowFlexScanResHed: {
    height: 60,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignContent: 'center',
  },
  rowFlexIcon: {
    marginLeft: 30,
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  SectionStyle: {
    height: 40,
    marginRight: 35,
    margin: 10,
  },
  buttonStyle2: {
    backgroundColor: COLORS.primary,
    borderWidth: 0,
    color: COLORS.white,
    height: 26,
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    // marginLeft: 20,
  },
  itemTextStyle: {
    color: COLORS.black,
    fontSize: 17,
    fontWeight: 'bold',
  },
  itemPriceStyle: {
    textDecorationLine: 'line-through',
    color: COLORS.third,
    fontSize: 12,
    fontWeight: 'bold',
    marginRight: 20,
  },
  itemOfferStyle: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  itemSizeText: {
    color: COLORS.black,
    fontSize: 9,
    textAlign: 'center',
  },
  sizeDot: {
    borderColor: COLORS.primary,
    borderWidth: 1,
    width: 15,
    height: 15,
    marginLeft: 5,
    justifyContent: 'center',
    borderRadius: 30,
  },
  sizeDot2: {
    borderColor: COLORS.primary,
    borderWidth: 0,
    width: 15,
    height: 15,
    marginLeft: 5,
    justifyContent: 'center',
    borderRadius: 30,
  },
  colorDot: {
    backgroundColor: '#111111',
    width: 15,
    height: 15,
    borderRadius: 30,
  },
  colorDot2: {
    backgroundColor: '#FF0000',
    width: 15,
    height: 15,
    marginLeft: 5,
    borderRadius: 30,
  },
  colorDot3: {
    backgroundColor: '#000000',
    width: 15,
    height: 15,
    marginLeft: 5,
    borderRadius: 30,
  },
  desTitle: {
    color: COLORS.black,
    fontSize: 15,
    fontWeight: 'bold',
    marginLeft: 30,
  },
  gridView: {
    marginTop: 10,
    flex: 1,
  },
  itemContainer: {
    justifyContent: 'flex-end',
    borderRadius: 5,
    padding: 10,
    height: 50,
  },
  itemName: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  itemCode: {
    fontWeight: '600',
    fontSize: 12,
    color: '#fff',
  },
});

export default styles;
